# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generate random variables from a multivariate Gaussian distribution
#'
#' This function uses the Cholesky decomposition to transform
#' isotropic Gaussian samples to samples from the desired Gaussian distribution
#' @param n The number of samples
#' @param mu The mean vector
#' @param sigma The variance-covariance matrix
#' @return A matrix of random draws from the specified Gaussian distribution
#' @export
rMvNorm <- function(n, mu, sigma) {
    .Call('_MetaNorm_rMvNorm', PACKAGE = 'MetaNorm', n, mu, sigma)
}

#' Compute matrix inverse
#'
#' This function computes the inverse of the supplied matrix
#' @param sig A matrix to be inversed
#' @return The inverse of the supplied matrix
#' @export
inverse <- function(sig) {
    .Call('_MetaNorm_inverse', PACKAGE = 'MetaNorm', sig)
}

#' A helper function of the Gibbs sampler to the Sigma parameters of a_{ik} and b_{ik}
#'
#' This function computes the posterior covariance matrix
#' of the parameter theta_{ik} = (a_{ik} and b_{ik})
#' @param Sig The current posterior sample of the covariance matrix
#' @param X A matrix of X_{ik}
#' @param sigjk A diagonal matrix of the posterior samples of sigma^2_{jk}
#' @return An updated Sigma matrix
#' @export
Sig1_cpp <- function(Sig, X, sigjk) {
    .Call('_MetaNorm_Sig1_cpp', PACKAGE = 'MetaNorm', Sig, X, sigjk)
}

#' A helper function of the Gibbs sampler to mu the parameters a_{ik} and b_{ik}
#'
#' This function computes the posterior mean vector
#' of the parameter theta_{ik} = (a_{ik} and b_{ik})
#' @param Sig1 The updated posterior covariance matrix
#' @param Sig The current posterior sample of the covariance matrix
#' @param X X A matrix of X_{ik}
#' @param sigjk A diagonal matrix of the posterior samples of sigma^2_{jk}
#' @param m The current posterior sample of the mean vector
#' @param Y A vector of Y_{ik}
#' @param s A vector of s_k
#' @return An updated mu vector
#' @export
mu_cpp <- function(Sig1, Sig, X, sigjk, m, Y, s) {
    .Call('_MetaNorm_mu_cpp', PACKAGE = 'MetaNorm', Sig1, Sig, X, sigjk, m, Y, s)
}

